### ISSUE TITLE
hw.h library for raspberry pi 3 or 3

### ISSUE THREAD

**Issue by Rahul828086** [offis/raspi-directhw#1]
can anyone please help me with hw.h file for rapsberry pi 2 or 3. i want to use pi as in spi slave mode.

**Comment by jwalt** [comment]
This library was written for the Pi 1, and I guess it will not work out-of-the-box with a newer one. Unfortunately, I don't have a Pi 2 or 3 to test things.

If you get the reference manual of the SoCs on the Pi 2 or Pi 3, you may be able to adapt the addresses and register definitions present in hw.h, but I really have no idea if it is that easy. If you do try this, please let me know your findings.

**Comment by Rahul828086** [comment]
Is changing the offset and base address is sufficient to make it work for pi 2?

**Comment by peterfortress** [comment]
> Is changing the offset and base address is sufficient to make it work for pi 2?

hi Rahul828086, 
do you find the solution for pi 3?.  I need spi slave mode too

**Comment by Rahul828086** [comment]
> > Is changing the offset and base address is sufficient to make it work for pi 2?
> 
> hi Rahul828086,
> do you find the solution for pi 3?. I need spi slave mode too

no coundn't . you can make a software bit bang using interrupts in BCM library and make work as spi.

**Comment by peterfortress** [comment]
> > > Is changing the offset and base address is sufficient to make it work for pi 2?
> > 
> > 
> > hi Rahul828086,
> > do you find the solution for pi 3?. I need spi slave mode too
> 
> no coundn't . you can make a software bit bang using interrupts in BCM library and make work as spi.

thank you. I changed the base address  ( #define ARM(x) ((x)+0x20000000ul)
 to #define ARM(x) ((x)+0x3f000000ul))  in pi 3   , the gpio_test.c works. Maybe the spi would be work. I am trying. Did you make sure you try spi? anyway, could you share your bit bang code? thank you very much.

**Comment by ghost** [comment]
my SPI clock frequency is 80K. it's too high  .I can not use pigpio library to bit bang.

**Comment by Rahul828086** [comment]
you can see for interrupt example and read specific pin and write other pin. thats how i made it work,

**Comment by peterfortress** [comment]
> you can see for interrupt example and read specific pin and write other pin. thats how i made it work,

HI Rahul828086,
I made the code work.  only #define ARM(x) ((x)+0x3f000000ul)) in pi 3  .  remember: spisl.h  is is for PCM. it's PCM to make an spi slave function. there is NO spi slave function for all of spi0, spi1 and spi2(there are only master). so make sure the pin connection is correct!      
	gpio_configure(18, Alt0);
	gpio_configure(19, Alt0);
	gpio_configure(20, Alt0);
	gpio_configure(21, Alt0);
 and I set    		.FSI = 1,     		.FLEN = 0,   
so I can use PCM_FS  as frame sync(CS) , do NOT need software  function  static inline void spisl_synchronize(void)  to sync.
I share my work here. It's hard to work spi slave out. anyway, I worked it out

**Comment by peterfortress** [comment]
anyway I can not work out spi slave for BSC

**Comment by jwalt** [comment]
Thanks a lot for your investigation. I have pushed a small update that should work for Pi2/Pi3. I was unable to check if everything works, however, since I no longer have a SPI Slave setup available. If you test something, please drop me a line if it works (or open a new issue if it doesn't).

**Comment by peterfortress** [comment]
after changing something code ,It works in pi 3. I tested! 
remember: this code is to config  PCM to as a spi slave. these are NO spi slave in spi0, spi1 and spi2. all of spi0 spi1 and spi2 are spi master. there is a spi slave in BSC, but I tried,It could not work for me. maybe need someone to develop it.
I configed PCB as 16bits spi slave  with hardware sync . 

in file hw. I changed ( #define ARM(x) ((x)+0x20000000ul)
to #define ARM(x) ((x)+0x3f000000ul)) in pi 3

in file spisl.h I changed:   in PI3, I used PCM 18,19,20,12 please read "BCM2837 ARM Peripherals" page 102

#if 0
	gpio_configure(28, Alt2);
	gpio_configure(29, Alt2);
	gpio_configure(30, Alt2);
	gpio_configure(31, Alt2);
#endif
#if 1
	gpio_configure(18, Alt0);
	gpio_configure(19, Alt0);
	gpio_configure(20, Alt0);
	gpio_configure(21, Alt0);
#endif
...

HW.PCM.RXC.B.CH1WID = 8; //0 is for 8 bits;  8 is for 16 bits(my application)

...
sync setting: must set FLEN is 0 ,read careful peripherals page 121 for sync


		.FLEN = 0,//7 0 is OK sync   peripherals page 121 for sync
 		.FSLEN =0,//7,
		.CLKM = 1,   // 1
		.CLKI = 0,    // 0    0:falling edge,1:rising edge.  0 is OK
		.FSM = 1,
		.FSI = 1,// 1,  1 is OK falling edge, 0 is rising edge ? we use 0?
		.CLK_DIS = 1,
 


done!

Thank you jwalt and Rahul828086, I passed the most important step for my project!
